const actionTypes = {
  CREATE_ITEM: "CREATE_ITEM",
  GET_ITEMS_LIST: "GET_ITEMS_LIST",
  SET_SELECTED_ITEM: "SET_SELECTED_ITEM",
  SET_ADD_MODAL: "SET_ADD_MODAL",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  SET_SELECTED_FILTER: "SET_SELECTED_FILTER",
};
export default actionTypes;
